basePath: /
definitions:
  giris.AuthObject:
    properties:
      kadi:
        type: string
      sifre:
        type: string
    type: object
  giris.girisResult200:
    properties:
      takim_no:
        type: string
    type: object
  giris.girisResult500:
    properties:
      error:
        type: string
    type: object
  sunucusaati.ServerTime:
    properties:
      dakika:
        type: integer
      gun:
        type: integer
      milisaniye:
        type: integer
      saat:
        type: integer
      saniye:
        type: integer
    type: object
  telemetri_gonder.TelemetryData:
    properties:
      gps_saati:
        properties:
          dakika:
            type: integer
          milisaniye:
            type: integer
          saat:
            type: integer
          saniye:
            type: integer
        type: object
      hedef_genislik:
        type: integer
      hedef_merkez_X:
        type: integer
      hedef_merkez_Y:
        type: integer
      hedef_yukseklik:
        type: integer
      iha_batarya:
        type: integer
      iha_boylam:
        type: number
      iha_dikilme:
        type: integer
      iha_enlem:
        type: number
      iha_hiz:
        type: integer
      iha_irtifa:
        type: integer
      iha_kilitlenme:
        type: integer
      iha_otonom:
        type: integer
      iha_yatis:
        type: integer
      iha_yonelme:
        type: integer
      takim_numarasi:
        type: integer
    type: object
  telemetri_gonder.TelemetryDataResponse:
    properties:
      konumBilgileri:
        items:
          $ref: '#/definitions/telemetri_gonder.TelemetryData'
        type: array
      sunucusaati:
        $ref: '#/definitions/sunucusaati.ServerTime'
    type: object
host: 127.0.0.1:3000
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Example API
  version: "1.0"
paths:
  /api/giris:
    post:
      consumes:
      - application/json
      description: Status Code'lar kesin olarak bu şekilde, 200 dönütünde aldığımız
        obje farklı olabilir (!)
      parameters:
      - description: Giriş Bilgileri
        in: body
        name: AuthObject
        required: true
        schema:
          $ref: '#/definitions/giris.AuthObject'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/giris.girisResult200'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/giris.girisResult500'
      summary: Giriş Yapmak için kullanılır
      tags:
      - giris
  /api/sunucusaati:
    get:
      consumes:
      - application/json
      description: Sunucu saatini sorgulamak için kullanılır
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sunucusaati.ServerTime'
      summary: Sunucu Saatini Gönderir
      tags:
      - sunucu saati
  /api/telemetri_gonder:
    post:
      consumes:
      - application/json
      description: Hava aracının bilgilerini anlık olarak sunucuya göndermek ve diğer
        takımların bilgilerini almak için kullanılır
      parameters:
      - description: Telemetri Bilgileri
        in: body
        name: TelemetryData
        required: true
        schema:
          $ref: '#/definitions/telemetri_gonder.TelemetryData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/telemetri_gonder.TelemetryDataResponse'
        "400":
          description: Bad Request
      summary: Telemetri Göndermek için kullanılır
      tags:
      - Telemetri Gönder
swagger: "2.0"
